package com.aresstack.pyloros.intellij;

final class SkillTexts {

    static final String CLEAN_CODE_REFACTORING = String.join("\n",
            "# IntelliJ MCP Steroids Clean Code Refactoring Skill",
            "",
            "## Purpose",
            "",
            "Use this skill when refactoring Java code in IntelliJ through mcp-steroid__steroid_execute_code.",
            "",
            "The goal is to produce Clean Code-style improvements using IntelliJ's semantic model instead of fragile text replacement.",
            "",
            "## Core Rules",
            "",
            "- Prefer IntelliJ PSI, refactoring processors, inspections, and project model APIs over raw file editing.",
            "- Use literal text replacement only for tiny mechanical edits where no semantic API exists.",
            "- For symbol changes, use real refactorings: Rename, Move, Safe Delete, Extract Method, Change Signature, Inline Method.",
            "- Do a dry run before any complex refactoring.",
            "- Apply only one coherent refactoring step at a time.",
            "- Validate after each applied step with file inspections and build.",
            "- Keep Java 8 compatibility unless the project explicitly allows newer language features.",
            "- Prefer focused methods with intention-revealing names.",
            "- Preserve architectural boundaries.",
            "- Do not move Java classes by copy/delete when IntelliJ Move Refactoring can update packages and references.",
            "- Do not rename symbols by string replacement.",
            "- Do not delete symbols directly before checking usages or running Safe Delete.",
            "",
            "## Standard Workflow",
            "",
            "1. Discover the target through IntelliJ indexes.",
            "2. Read the target file with line numbers.",
            "3. Pick one Clean Code candidate.",
            "4. Run a dry run through the appropriate processor.",
            "5. Apply only if preparation succeeds.",
            "6. Save documents.",
            "7. Run inspections.",
            "8. Build.",
            "9. Report what changed, why, and the validation result.",
            "",
            "## Clean Code Heuristics",
            "",
            "Extract Method when a method contains a clearly named subtask, a block needs a comment, or a block reads like a separate step in a use case.",
            "",
            "Move Class when a class belongs to another layer or package by responsibility, or when a factory would reduce application wiring noise.",
            "",
            "Introduce Factory when construction logic obscures orchestration flow or creates different implementations of the same abstraction.",
            "",
            "Introduce Strategy when branching chooses behavior based on a mode, provider id, type, or transport.",
            "",
            "## Reporting Format",
            "",
            "Applied:",
            "- <refactoring summary>",
            "",
            "Why:",
            "- <readability / responsibility / coupling reason>",
            "",
            "Validation:",
            "- prepare(): <true|false>",
            "- inspections: <count / notable issues>",
            "- build: errors=<true|false>, aborted=<true|false>",
            "",
            "Notes:",
            "- <warnings, limitations, next suggested refactoring>"
    );

    private SkillTexts() {
    }
}
